# Generated by Django 2.1.1 on 2018-11-17 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_point', models.CharField(max_length=2)),
                ('professor', models.CharField(max_length=100, null=True)),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configq.CourseName')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topLeftX', models.SmallIntegerField()),
                ('topLeftY', models.SmallIntegerField()),
                ('bottomRightX', models.SmallIntegerField()),
                ('bottomRightY', models.SmallIntegerField()),
                ('page', models.SmallIntegerField()),
                ('questionText', models.TextField(blank=True, max_length=500)),
                ('questionAns', models.TextField(blank=True, max_length=200)),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configq.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configq.Semester'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('course_name', 'semester')},
        ),
    ]
