# Generated by Django 2.1.1 on 2018-11-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='Exam',
            new_name='exam',
        ),
    ]
