# Generated by Django 2.1.1 on 2018-11-18 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0002_auto_20181118_0102'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configq.Exam')),
            ],
        ),
    ]
