# Generated by Django 2.1.1 on 2018-11-27 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0002_auto_20181127_0909'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pageconfig',
            old_name='exam',
            new_name='upload_question',
        ),
    ]
