# Generated by Django 2.1.1 on 2018-11-19 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0004_auto_20181119_0248'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uploadquestion',
            unique_together={('exam', 'page')},
        ),
    ]
