# Generated by Django 2.1.1 on 2018-11-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0005_auto_20181119_1306'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('exam', 'page', 'question_number')},
        ),
    ]
