# Generated by Django 2.1.1 on 2018-11-20 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0007_auto_20181120_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questionAns',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='questionText',
            field=models.TextField(max_length=500),
        ),
    ]
