# Generated by Django 2.1.1 on 2018-11-27 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0007_auto_20181127_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageconfig',
            name='upload_question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='configq.UploadQuestion'),
        ),
    ]
