# Generated by Django 2.1.1 on 2018-11-22 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0008_auto_20181120_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.SmallIntegerField()),
                ('mat_digit_count', models.SmallIntegerField()),
                ('mat_digit_1_top_left_x', models.SmallIntegerField()),
                ('mat_digit_1_top_left_y', models.SmallIntegerField()),
                ('mat_digit_1_bottom_right_x', models.SmallIntegerField()),
                ('mat_digit_1_bottom_right_y', models.SmallIntegerField()),
                ('mat_digit_2_top_left_x', models.SmallIntegerField()),
                ('mat_digit_2_top_left_y', models.SmallIntegerField()),
                ('mat_digit_2_bottom_right_x', models.SmallIntegerField()),
                ('mat_digit_2_bottom_right_y', models.SmallIntegerField()),
                ('mat_digit_3_top_left_x', models.SmallIntegerField()),
                ('mat_digit_3_top_left_y', models.SmallIntegerField()),
                ('mat_digit_3_bottom_right_x', models.SmallIntegerField()),
                ('mat_digit_3_bottom_right_y', models.SmallIntegerField()),
                ('mat_digit_4_top_left_x', models.SmallIntegerField()),
                ('mat_digit_4_top_left_y', models.SmallIntegerField()),
                ('mat_digit_4_bottom_right_x', models.SmallIntegerField()),
                ('mat_digit_4_bottom_right_y', models.SmallIntegerField()),
                ('mat_digit_5_top_left_x', models.SmallIntegerField()),
                ('mat_digit_5_top_left_y', models.SmallIntegerField()),
                ('mat_digit_5_bottom_right_x', models.SmallIntegerField()),
                ('mat_digit_5_bottom_right_y', models.SmallIntegerField()),
                ('mat_digit_6_top_left_x', models.SmallIntegerField()),
                ('mat_digit_6_top_left_y', models.SmallIntegerField()),
                ('mat_digit_6_bottom_right_x', models.SmallIntegerField()),
                ('mat_digit_6_bottom_right_y', models.SmallIntegerField()),
                ('mat_digit_7_top_left_x', models.SmallIntegerField()),
                ('mat_digit_7_top_left_y', models.SmallIntegerField()),
                ('mat_digit_7_bottom_right_x', models.SmallIntegerField()),
                ('mat_digit_7_bottom_right_y', models.SmallIntegerField()),
                ('page_no_top_left_x', models.SmallIntegerField()),
                ('page_no_top_left_y', models.SmallIntegerField()),
                ('page_no_bottom_right_x', models.SmallIntegerField()),
                ('page_no_bottom_right_y', models.SmallIntegerField()),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configq.Exam')),
            ],
        ),
    ]
