# Generated by Django 2.1.1 on 2018-11-27 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0008_auto_20181127_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageconfig',
            name='id',
        ),
        migrations.AlterField(
            model_name='pageconfig',
            name='upload_question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='configq.UploadQuestion'),
        ),
    ]
