# Generated by Django 2.1.1 on 2018-11-28 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0009_auto_20181127_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
