# Generated by Django 2.1.1 on 2019-02-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0010_exam_exam_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='allotedMarks',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
            preserve_default=False,
        ),
    ]
