# Generated by Django 2.1.1 on 2019-03-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0011_auto_20190201_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='grade_1_0',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_1_3',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_1_7',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_2_0',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_2_3',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_2_7',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_3_0',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_3_3',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_3_7',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_4_0',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='exam',
            name='grade_5_0',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=4),
        ),
    ]
