# Generated by Django 2.1.1 on 2018-12-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configq', '0010_exam_exam_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageParameter',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('configq.pageconfig',),
        ),
    ]
