# Generated by Django 2.1.1 on 2018-12-09 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0010_exam_exam_code'),
        ('grader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentAns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matriculation_num', models.CharField(max_length=10)),
                ('question_num', models.CharField(max_length=5)),
                ('students_ans', models.TextField(max_length=500)),
                ('matching_confidence', models.DecimalField(decimal_places=2, max_digits=3)),
                ('auto_grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('final_grade', models.DecimalField(decimal_places=2, max_digits=4)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configq.Exam')),
            ],
        ),
    ]
