# Generated by Django 2.1.1 on 2018-12-09 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configq', '0010_exam_exam_code'),
        ('grader', '0002_studentans'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentans',
            unique_together={('exam', 'matriculation_num', 'question_num')},
        ),
    ]
