# Generated by Django 2.1.1 on 2019-03-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0004_auto_20181209_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentans',
            name='maulally_graded',
            field=models.BooleanField(default=False),
        ),
    ]
