# Generated by Django 2.1.1 on 2019-03-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grader', '0005_studentans_maulally_graded'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentans',
            old_name='maulally_graded',
            new_name='manually_graded',
        ),
    ]
